export default {
    container: {
        paddingLeft: 18,
        background: '#F4F5F8',
        margin: '0 0px 10px',
        WebkitUserSelect: 'none',
        KhtmlUserSelect: 'none',
        MozUserSelect: 'none',
        MsUserSelect: 'none',
        UserSelect: 'none',
    },
    gridItem: {
        marginRight: 40,
    },
    checkbox: {
        fontSize: 10,
        position: 'relative',
        top: 2,
        color: 'transparent',
        background: 'white',
        border: '1px solid #dedede',
        borderRadius: 3,
    },
    checkboxChecked: {
        fontSize: 14,
        marginBottom: -2,
        marginRight: -2,
        position: 'relative',
        top: 1,
        right: 1,
    },
    stopIcon: {
        position: 'relative',
        top: 5,
        color: '#a6a7a6',
        fontSize: '14px',
        margin: '0px 3px 0px -9px',
    },
    text: {
        fontSize: '90%',
        cursor: 'pointer',
        color: '#000',
        position: 'relative',
        top: '3px',
    },
};
