export default {
    // PERIOD TYPE
    SET_PERIOD_TYPE: 'SET_PERIOD_TYPE',
    // OFFERED PERIODS
    ADD_OFFERED_PERIODS: 'ADD_OFFERED_PERIODS',
    REMOVE_OFFERED_PERIODS: 'REMOVE_OFFERED_PERIODS',
    TOGGLE_OFFERED_PERIOD: 'TOGGLE_OFFERED_PERIOD',
    // SELECTED PERIODS
    ADD_SELECTED_PERIODS: 'ADD_SELECTED_PERIODS',
    REMOVE_SELECTED_PERIODS: 'REMOVE_SELECTED_PERIODS',
    TOGGLE_SELECTED_PERIOD: 'TOGGLE_SELECTED_PERIOD',
}
